### ISSUE TITLE
Saving keybindings but not loading them 

### ISSUE THREAD

**Issue by nuubcake11** [rhodan412/ActionBarProfiles#1]
**Which version are you using when bug occurred**
Last available version

**Describe the bug**
I create a new profile, save profile, keybindings, macros, etc (all options), and when I take a spell away from action bars to test the addon, it loads the action bars but won't load the keybindings.
Example: Number 5 is Ice lance by default, I bound it to X -> Test with addon, X isn't binded.

**LUA Error**
If applicable, add to help detail what error codes may exist.

**To Reproduce**
1. Go to Addon Panel
2. Click on Use
3. Key binds not loading

**Expected behavior**
Keybinds should be loaded

**Comment by rhodan412** [comment]
I've identified the resolved the issue and will push an update on the restore of the keybinding once I've resolved #2 

If you wanted to preemptively resolve this issue and test if issues still exist, then change line 95 from this:
--self:RestoreBindings(profile, check, cache, res)

to this:
self:RestoreBindings(profile, check, cache, res)

**Comment by nuubcake11** [comment]
Thanks for the reply. 

I've changed the line, tested in-game and everyting is working fine! Thank you!

**Comment by rhodan412** [comment]
Glad it worked. I'm going to drop a comment regarding #2 as well so you can get an update on that issue
